os: windows
language: node_js
node_js:
  - 10
git:
  submodules: false
before_install:
  - ls
  - cd client/node_ui
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
install:
  - yarn install
script:
  - yarn dist
