os: windows
language: node_js
node_js:
  - 10
git:
  submodules: false
before_install:
  - cd client/node-ui
  - git submodule update --init
  - sed -i 's/git@github.com:/https:\/\/github.com\//' node-compositor/.gitmodules
  - git submodule update --init --recursive
install:
  - yarn install
script:
  - yarn dist
