matrix:
  allow_failures:
    - os: osx
os:
  - windows
  - osx
osx_image: xcode11
language: node_js
node_js:
  - 10
env:
  - YARN_GPG=no
git:
  submodules: false
before_install:
  - cd client/node-ui
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.17.3
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn install
script:
  - yarn dist
